apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  labels:
    app: kube-prometheus-stack-grafana
    grafana_datasource: "1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: "15.4.4"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-15.4.4
    release: "kube-prometheus-stack"
    heritage: "Helm"
data:
  datasource-loki.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki:3100/
      isDefault: false
      org_id: 1
      editable: true